# -*- coding: utf-8 -*-
"""se3_control.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15XauKamkDdADDq5JaC7Rer4PvUK3ue2J
"""

import numpy as np
from scipy.spatial.transform import Rotation

class SE3Control(object):
    """

    """
    def __init__(self, quad_params):
        """
        This is the constructor for the SE3Control object. You may instead
        initialize any parameters, control gain values, or private state here.

        For grading purposes the controller is always initialized with one input
        argument: the quadrotor's physical parameters. If you add any additional
        input arguments for testing purposes, you must provide good default
        values!

        Parameters:
            quad_params, dict with keys specified by crazyflie_params.py

        """

        # Quadrotor physical parameters.
        self.mass            = quad_params['mass'] # kg
        self.Ixx             = quad_params['Ixx']  # kg*m^2
        self.Iyy             = quad_params['Iyy']  # kg*m^2
        self.Izz             = quad_params['Izz']  # kg*m^2
        self.arm_length      = quad_params['arm_length'] # meters
        self.rotor_speed_min = quad_params['rotor_speed_min'] # rad/s
        self.rotor_speed_max = quad_params['rotor_speed_max'] # rad/s
        self.k_thrust        = quad_params['k_thrust'] # N/(rad/s)**2
        self.k_drag          = quad_params['k_drag']   # Nm/(rad/s)**2

        # You may define any additional constants you like including control gains.
        self.inertia = np.diag(np.array([self.Ixx, self.Iyy, self.Izz])) # kg*m^2
        self.g = 9.81 # m/s^2
        self.Kd = np.zeros((3,3)) #PD controller, gain matrix Kd
        np.fill_diagonal(self.Kd, [3,3.53,7.75])
        self.Kp = np.zeros((3,3)) #PD ontroller, gain matrix Kp
        np.fill_diagonal(self.Kp, [4.3,5.075,25])
        self.KR = np.zeros((3,3)) #rotation gain matrix K_R
        np.fill_diagonal(self.KR, [54, 45, 39.5102])
        self.Komg = np.zeros((3,3)) #angular velocity gain matrix K_omega
        np.fill_diagonal(self.Komg, [8.5, 6.2, 8.8])

        # STUDENT CODE HERE

    def update(self, t, state, flat_output):
        """
        This function receives the current time, true state, and desired flat
        outputs. It returns the command inputs.

        Inputs:
            t, present time in seconds
            state, a dict describing the present state with keys
                x, position, m
                v, linear velocity, m/s
                q, quaternion [i,j,k,w]
                w, angular velocity, rad/s
            flat_output, a dict describing the present desired flat outputs with keys
                x,        position, m
                x_dot,    velocity, m/s
                x_ddot,   acceleration, m/s**2
                x_dddot,  jerk, m/s**3
                x_ddddot, snap, m/s**4
                yaw,      yaw angle, rad
                yaw_dot,  yaw rate, rad/s

        Outputs:
            control_input, a dict describing the present computed control inputs with keys
                cmd_motor_speeds, rad/s
                cmd_thrust, N (for debugging and laboratory; not used by simulator)
                cmd_moment, N*m (for debugging; not used by simulator)
                cmd_q, quaternion [i,j,k,w] (for laboratory; not used by simulator)
        """
        cmd_motor_speeds = np.zeros((4,))
        cmd_thrust = 0
        cmd_moment = np.zeros((3,))
        cmd_q = np.zeros((4,))

        # STUDENT CODE HERE
        # compute F_des
        r_ddot_des = flat_output['x_ddot']-self.Kd @ np.array([-state['v'][0]+flat_output['x_dot'][0],-state['v'][1]+flat_output['x_dot'][1],state['v'][2]-flat_output['x_dot'][2]])-self.Kp @ np.array([-state['x'][0]+flat_output['x'][0],-state['x'][1]+flat_output['x'][1],state['x'][2]-flat_output['x'][2]])
        # r_ddot_des = flat_output['x_ddot']-self.Kd @(state['v']-flat_output['x_dot'])-self.Kp @(state['x']-flat_output['x'])
        # print('e_p=',state['x']-flat_output['x'],'e_v=',state['v']-flat_output['x_dot'])
        F_des = self.mass*r_ddot_des + np.array([0,0,self.mass*self.g])
        q = state['q']
        R = Rotation.from_quat(q).as_matrix()
        b3 = R @ np.array([0,0,1])
        u1 = b3.T @ F_des
        # compute R_des
        b3_des = F_des/np.linalg.norm(F_des,2)
        sai_T = flat_output['yaw']
        a_sai = np.array([np.cos(sai_T),np.sin(sai_T),0])
        b2_des = np.cross(b3_des,a_sai)/np.linalg.norm(np.cross(b3_des,a_sai),2)
        R_des = np.array([np.cross(b2_des,b3_des),b2_des,b3_des])
        
        # compute e_R
        e_R = np.zeros(3)
        e_R_ = R_des.T@R-R.T@R_des
        e_R[0] = 0.5*e_R_[2,1]
        e_R[1] = 0.5*e_R_[0,2]
        e_R[2] = 0.5*e_R_[1,0]
        # print('e_R=',e_R,'e_omega=',state['w'])
        # compute u2
        e_omg = state['w']
        # print('angular error=',e_omg)
        I = np.zeros((3,3))
        I[0,0] = self.Ixx
        I[1,1] = self.Iyy
        I[2,2] = self.Izz
        u2 = I@(-self.KR@e_R - self.Komg@e_omg)
        # print('u2=',u2)
        # compute command motor speeds
        yita = self.k_drag/self.k_thrust
        u = np.zeros(4)
        u[0] = u1
        u[1:4] = u2
        F_coe = np.array([[1,1,1,1],[0,self.arm_length,0,-self.arm_length],[-self.arm_length,0,self.arm_length,0],[yita,-yita,yita,-yita]])
        F = np.linalg.inv(F_coe)@ u
        # print('kd=',self.Kd,'kp=',self.Kp,'k_R=',self.KR,'k_omega=',self.Komg)
        # print('k_R=',self.KR,'k_omega=',self.Komg)
        cmd_motor_speeds = np.sqrt(np.maximum(F/self.k_thrust,np.zeros(4)))
        cmd_thrust = np.sum(F)
        # print('command thrust=',cmd_thrust)
        cmd_moment = np.array([[0,self.arm_length,0,-self.arm_length],[-self.arm_length,0,self.arm_length,0],[yita,-yita,yita,-yita]])@F

        control_input = {'cmd_motor_speeds':cmd_motor_speeds,
                         'cmd_thrust':cmd_thrust,
                         'cmd_moment':cmd_moment,
                         'cmd_q':cmd_q}
        return control_input

